[package]
name = "rustfetch"
version = "0.1.0"
edition = "2024"
authors = ["mustafa 'pxsty' k√∂k <pxsty@pxserv.net>"]
license = "MIT"

[dependencies]
sysinfo = { version = "0.30" }
os_info = "3"
owo-colors = "4"
which = "6"
regex = "1"
whoami = "1.5"
